services:
  research-mcp:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: research-mcp:latest
    container_name: research-mcp
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - NODE_ENV=production
      # Search indexing configuration
      - SEARCH_DB_PATH=/app/data/search.db
      - RESEARCH_ARCHIVE_PATH=/app/data/research-archive
      - URL_CONTENT_ARCHIVE_PATH=/app/data/url-content-archive
      - INDEXING_SCHEDULE=0 * * * *  # Run indexing every hour
      - WATCH_FILES=true
    env_file:
      - ./src/.env
    volumes:
      # For persistent storage of search indexing
      - ./data:/app/data
      - ./data/research-archive:/app/data/research-archive
      - ./data/url-content-archive:/app/data/url-content-archive
      # For logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
